### ISSUE TITLE
Kirjaudu ulos -toiminto ei kirjaa käyttäjää ulos järjestelmästä

### ISSUE THREAD

**Issue by minna-aaltonen** [Tietoarkisto/metka#131]
Jos sisäänkirjautunut käyttäjä (käyttäjä 1) kirjautuu ulos METKA:sta valitsemalla "Kirjaudu ulos" ja samalta koneelta kirjaudutaan uudelleen toisilla tunnuksilla (käyttäjä 2), METKA:n kirjautuminen tapahtuukin edellisenä käyttäjänä (käyttäjä 1).

**Comment by LaKulmala** [comment]
Kyseessä on asia joka on Shibboleth tyylisten järjestelmien kanssa erittäin vaikea toteuttaa. 20.5.2015 palaverissa päätettiin että tämän mahdollistamiseen ei tarvitse käyttää työaikaa koska reaalikäytössä tilanne ei yleisesti tule vastaan (kaikilla käyttäjillä on vain yksi käyttäjätunnus)
