### ISSUE TITLE
Aineistot | Virheet | Herätepäivämäärä: Väärän muotoisen päivämäärän virheenkäsittely puuttuu

### ISSUE THREAD

**Issue by minna-aaltonen** [Tietoarkisto/metka#177]
Väärän muotoinen päivämäärä (esim. kirjaimet) aiheuttaa seuraavan virheen:

Virhe

HTTP Status 400 -

type Status report

message

description The request sent by the client was syntactically incorrect ().
Apache Tomcat/7.0.28

**Comment by LaKulmala** [comment]
Koska virheet muutetaan revisio-objektiksi ( #366 ) niin tämä issue ei ole ajankohtainen. Suljen pois.
