### ISSUE TITLE
Massapäivitys: por-tiedoston vieminen APIn kautta ei käynnistä tiedoston käsittelyä

### ISSUE THREAD

**Issue by matti-heinonen** [Tietoarkisto/metka#214]
Muuttujatiedoston (.por) tietojen tallentaminen APIn kautta ei käynnistä tiedoston käsittelyä. Kun samat tiedot tallenttaa kälistä muutoksitta, käsittely käynnistyy. Tämä estää massapäivitysten tekemisen APIn kautta.

**Comment by LaKulmala** [comment]
Kts. issuen #189 kommentti

**Comment by LaKulmala** [comment]
Korjaantuu automaattisesti issuen #189 muutosten kanssa joten suljen pois.
