### ISSUE TITLE
GUI: sivuttamattomat listat: suorituskyky loppuu

### ISSUE THREAD

**Issue by matti-heinonen** [Tietoarkisto/metka#221]
Aineiston "Tiedostojen hallinta"-välilehti on käyttökelvoton, kun liitetiedostoja on paljon (esim. FSD2104: 3512 liitettä). Sivun lataamisessa kestää kymmeniä sekunteja ja Firefox jäätyy välillä täysin. 

Tarjouspyynnön mukaan Metkan pitäisi suoritutua tuhansista tietoelementtien ilmentymistä per aineisto.

**Comment by matti-heinonen** [comment]
Edelleen olemassa. Pitkät listaukset latautuvat todella hitaasti.

**Comment by matti-heinonen** [comment]
Tämä koskee ilmeisesti kaikki asivuttamattomia listauksia.

**Comment by katja-moilanen** [comment]
Ongelma edelleen olemassa mm. muuttujasivustolla, jossa voi olla tuhansia muuttujia.

**Comment by henrisu** [comment]
#858 lisätty muuttujasivulle ja tiedostojen hallintaan sivutus (rowsPerPage)

**Comment by Quu-Ukko** [comment]
Korjaus toimii hyvin muuttujien kanssa. Tiedostoliitteiden kanssa Metka ei vastaa ennen kuin sivutus on valmis.  Testasin edellä mainitulla yli tuhannen liitteen aineistolla ja Metka ei reagoinut syötteisiin 1.5 minuuttiin.

**Comment by Quu-Ukko** [comment]
FSD2104 vastasi syötteisiin 18 sekunnin jälkeen. Suljen issuen

**Comment by henrisu** [comment]
Laitoin resolved-labelin vielä. Issuen #497 ongelma ratkennee myös tämän myötä, merkitsen senkin resolvediksi.
