### ISSUE TITLE
Aineisto, joka on saatu hyväksyttyäkin lakkasi indeksoitumasta eikä löydy hakujen kautta.

### ISSUE THREAD

**Issue by katja-moilanen** [Tietoarkisto/metka#232]

**Comment by LaKulmala** [comment]
Suljen myös tämän sillä en yksinkertaisesti pysty näillä tiedoilla mitään selvittämään. Jos vastaavaa tilannetta vielä ilmenee niin tarvitsen json-tiedostot aineistosta jossa ongelma ilmenee sekä kaikista siihen liittyvistä liitetiedostoista ja muuttujista sillä ongelma voi sijaita missä tahansa näistä tiedoista. Ennakoiduista indeksoinnin virhetilanteista tulee myös logimerkinnät joten nämäkin olisi hyvä olla mukana. Vaihtoehtoisesti ongelmallisen tiedon haarukointi testaajan puolelta nopeuttaa ongelman korjaamista, eli luodaan uusi aineisto johon syötetään ongelmallisen aineiston tiedot yksi kerrallaan ja tarkistetaan indeksoituminen aina uuden tiedon jälkeen. Ongelmallinen tieto löytyy näin todennäköisesti tiedosta jonka syötön jälkeen aineisto ei enää indeksoidu (ellei kyseessä ole jokin ennalta-arvaamaton tietojen yhdistelmän aiheuttama ongelma).
