### ISSUE TITLE
Mappitiedon klikkaaminen aiheuttaa satunnaisesti seuraavan virheilmoituksen

### ISSUE THREAD

**Issue by katja-moilanen** [Tietoarkisto/metka#246]
![virheilmo_kun_tuplaklikkasi_aineiston_mappia](https://cloud.githubusercontent.com/assets/8694364/5261710/5ad31c4e-7a25-11e4-95c7-e893f6fb380c.JPG)

Dec 02, 2014 1:06:12 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [web] in context with path [/metka-ap] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
java.lang.NullPointerException

Dec 02, 2014 1:06:12 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [web] in context with path [/metka-ap] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
java.lang.NullPointerException

**Comment by LaKulmala** [comment]
Tähän joudun valitettavasti toteamaan saman kuin issueen #298 eli en pysty tällä tiedolla ongelmaa selvittämään. Myöskin mappitietoihin on tehty muutoksia ja korjauksia tämän issuen kirjaamisen jälkeen joten on mahdollista että ongelma on korjattu. Jos ilmenee uudelleen niin avataan uusi issue täydellisellä virheviestillä.
