### ISSUE TITLE
DDI import ei toimi

### ISSUE THREAD

**Issue by katja-moilanen** [Tietoarkisto/metka#283]
Aukeaa kyllä ikkuna, jossa annetaan tiedoston polku, mutta mitään ei tapahdu - ei tule edes virheilmoitusta.

**Comment by katja-moilanen** [comment]
Jotain toiminnallisuutta on ja virheilmoituksiakin sain aikaan. Selvää on, ettei tämä toiminnallisuus ole valmis.

**Comment by tiinaisotalo** [comment]
Liitätkö tähän virheilmoituksen, sekä kuvauksen puuttuvasta toiminnallisuudesta.

**Comment by LaKulmala** [comment]
Suljetaan tämä pois koska issuen kuvaus ei kerro mitään mahdollisista ongelmista. Meidän testien mukaan DDI-import tuo ne tiedot jotka DDI:n rajoitteiden myötä on mahdollista tuoda. Jos jotain virheviestejä tai puutteita vielä ilmenee niin tehdään niistä omat issuet tarkoilla kuvauksilla ja virheviesteillä.
