### ISSUE TITLE
Hyväksy-napin runsas painelu aineistolle, jota ei hyväksytä johtaa virheilmoon

### ISSUE THREAD

**Issue by katja-moilanen** [Tietoarkisto/metka#293]
![virheilmo_hyvaksynta_napin_painelu](https://cloud.githubusercontent.com/assets/8694364/5314968/b954800c-7c80-11e4-80be-646d6cb3d7dc.png)

**Comment by LaKulmala** [comment]
Jälleen sama kommentti kuin #298. Lisäksi virheen kuvaus ei kerro taroitetaanko 'runsaalla painelulla' painamista nopeaan tahtiin ennen kuin järjestelmä ehtii reagoimaan vai painamista useasti kuitenkin aina järjestelmän palautetta odottaen.
