### ISSUE TITLE
Hyväksy-napin painaminen aiheuttaa satunnaisesti virheilmoituksen

### ISSUE THREAD

**Issue by katja-moilanen** [Tietoarkisto/metka#298]
![hyvaksymis_napin_painallus](https://cloud.githubusercontent.com/assets/8694364/5315579/ef06cc12-7c87-11e4-8938-ce3df8d46b02.png)

**Comment by LaKulmala** [comment]
Virheviestikuvassa ei ole valitettavasti mukana vielä yhtään meidän koodiin viittaavaa riviä (olisivat olleet todennäköisesti viestissä myöhemmin) joten en tämän perusteella pysty tätä ongelmaa selvittämään. Hyväksymisessä vastaantulleet ongelmatilanteet on kuitenkin korjattu aina heti kun ne ovat omissa testeissä tulleet vastaan joten on hyvin mahdollista että tämä on korjaantunut pois.
Suljetaan tämä issue koska en tosiaan pysty näillä tiedoilla sitä selvittämään ja jos tilanne vielä tulee vastaan niin avataan uusi issue johon tulee mukaan täydellinen virheviesti.
