### ISSUE TITLE
BiblCitiin (eli viittaustietoihin) generoituu virheellistä tietoa

### ISSUE THREAD

**Issue by katja-moilanen** [Tietoarkisto/metka#315]
Biblcitiin tulee jsonissa ensimmäisenä olevan organisaation tiedot, vaikka sitä ei ole valittu pudotusvalikosta, ainakin seuraavissa tilanteissa:
1) on painettu tallenna-nappia, mutta mitään tietoa ei ole syötetty
2) koska GUI ei mukaudu tyypin mukaan, käyttäjä on valinnut organisaation ja syöttänyt tietoja henkilökenttään (peruskäyttäjältä puuttui oikeudet lisätä organisaatioita)
Tämä koskee tuottajaa ja aineiston kerääjää eli näille ilmestyy väärän organisaation tiedot biblcit-kenttään (mutta näyttäisi siltä, ettei tuottaja ja kerääjä -kenttiin sinänsä tallennu virheellistä tietoa).

**Comment by LaKulmala** [comment]
Koska UI mukautuu nyt valintojen mukaan (kts. #249 ) ja peruskäyttäjä pystyy nyt syöttämään organisaatioita (kts. #198 ) niin suljen tämän issuen pois. Jos virheellistä tietoa vielä generoituu niin sitten uusi issue ja sinne kuvaus virheellisestä tiedosta ja mitä oletettu tieto olisi pitänyt olla.
