### ISSUE TITLE
muuttujapuolella järjestyksen säilyttäminen / järjestäminen on olennaista, mutta järjestystä ei pysty muuttumaan esim. muuttujien ryhmittelyssä

### ISSUE THREAD

**Issue by katja-moilanen** [Tietoarkisto/metka#318]

**Comment by LaKulmala** [comment]
Varsinaisen muuttujataulukon järjestys tulee por-tiedostosta eikä sitä ole tarkoitus muuttaa käyttöliittymästä käsin. Muuttujaryhmien sisäinen järjestys käsitellään issuessa #256 
Tämä issue ei sisällä erillistä työtä joten suljen pois.
