### ISSUE TITLE
Biblcit-kenttää ei generoida, kun tallentaa aineiston tiedot APIn kautta

### ISSUE THREAD

**Issue by matti-heinonen** [Tietoarkisto/metka#332]
Kun tallentaa samat tiedot uudelleen kälistä, kenttä generoituu. Tämä estää APIn käyttämisen aineistojen muokkaukseen.

**Comment by LaKulmala** [comment]
Korjaantuu automaattisesti issuen #189 muutosten kanssa joten suljen pois.
