### ISSUE TITLE
Aineisto | Perustiedot | Kuvailun versiot: Kentät eivät ole käännettävissä vaikka pitäisi

### ISSUE THREAD

**Issue by minna-aaltonen** [Tietoarkisto/metka#359]
Aineisto | Perustiedot | Kuvailun versiot: kaikkien kenttien pitäisi olla käännettävissä, mutta eivät ole 
(vrt. karsittu_tietoelementtien_yhdistelmä.xlsx)

**Comment by LaKulmala** [comment]
Kuvailun versiot on ns. kääntyvä taulukko, eli eri kielillä on eri rivit (vrt. esim. Aineisto | Kuvailu | Aineistonkeruu | Lähdeaineistot). Kun kieleksi valitaan englanti tai ruotsi on käyttäjällä täytettävänä kaksi eri Kuvailun versiot kenttää joista toiseen syötetään suomenkieliset rivit ja toiseen käännöskielen rivit.
