### ISSUE TITLE
Aineistot | Tiedostojen hallinta | Lisää: Aineistolle ei voi lisätä liitetiedostoja

### ISSUE THREAD

**Issue by minna-aaltonen** [Tietoarkisto/metka#360]
Kun valisee aineistolle Tiedostojen hallinnassa **Lisää**, METKA avaa Muokkaa liitetiedostoa -dialogin, jossa **Tiedoston polku** kentää on inaktiivinen -> aineistolle ei voi listätä liitetiedostoa.

**Comment by LaKulmala** [comment]
Päivitykseen taisi eksyä mukaan osittainen alku issueen #335 liittyen. Pikaisesti katsoen ongelma oli pelkästään konfiguraatioissa joten korjasin käyttäen Asetukset sivua. Tällä viikolla tulee joka tapauksessa muuttunut toteutus tuosta liitteiden käsittelystä joten en lähde kommitoimaan muutosta GitHubiin.
