### ISSUE TITLE
DDI Export ei toimi

### ISSUE THREAD

**Issue by katja-moilanen** [Tietoarkisto/metka#388]
![ddi_export_ei_toimi](https://cloud.githubusercontent.com/assets/8694364/10335949/9fb80538-6cfd-11e5-8554-e6f9c96983f0.png)

Vain Sulje-nappi on näkyvissä eikä toisen napin "haamun" painaminen tee mitään.

Export-toiminnallisuutta ei voi testata.

**Comment by LaKulmala** [comment]
Tämä oli juuri se ominaisuus josta maananataina sanoin että on korjattu jo. Eli testaatteko uudella asennuksella ja katsotte sitten tämän issuen uudelleen.

**Comment by matti-heinonen** [comment]
Tämä liittyy käliin ja on vanhetunut. Suljetaan.
