### ISSUE TITLE
Aineiston tiedostoliitteitä ei voi poistaa peruskäyttäjän tunnuksilla.

### ISSUE THREAD

**Issue by katja-moilanen** [Tietoarkisto/metka#395]

**Comment by katja-moilanen** [comment]
ongelma edelleen olemassa

**Comment by juusokoH** [comment]
Permission lisätty, aineiston täytyy silti olla DRAFT-tilassa ja basic-user -käyttäjän hallussa, jotta tiedostoliitteitä voi poistaa
