### ISSUE TITLE
Virheellinen tiedostoliitteen lisäysikkuna

### ISSUE THREAD

**Issue by katja-moilanen** [Tietoarkisto/metka#418]
![title_tiedostojen_lisayksesta](https://cloud.githubusercontent.com/assets/8694364/10457078/51bf5e1a-71cd-11e5-8db1-7f3e21c4cac1.PNG)

Lisää-napin painaminen tiedostoliitenäytöllä avaa yllä olevan kuvan pop up -ikkunan.

**Comment by katja-moilanen** [comment]
Ongelma esiintyy mahdollisesti vain IE:llä

**Comment by katja-moilanen** [comment]
Samaa on nyt ilmennyt luonnoksen teon yhteydessä ja myös muilla selaimilla.

**Comment by LaKulmala** [comment]
Tästä ongelmasta mainitsin myös. Pitäisi korjaantua sivun uudelleenlatauksella. Jos näin on niin ei Blocker vaan Major.

**Comment by katja-moilanen** [comment]
Välillä korjaantuu uudelleenlatauksella, välillä ei.

**Comment by LaKulmala** [comment]
Tapahtuuko tuota välillä ei korjaantumista kaikilla selaimilla?
Onko toiminta aina samanlaista kun uudelleenlataus ei ole korjannut tilannetta?
Jääkö tilanne korjaantumatta välillä sellaisella aineistolla jolla tilanne välillä kuitenkin korjaantuu uudelleenlatauksella vai onko kyseessä aineistokohtainen ongelma?
Ladataanko sivu aina uudelleen samalla tavalla, esim. painamalla ctrl+r vai vaihdellaanko uudelleenlataustapaa?
Jos uudelleenlataustapaa vaihdellaan niin vaikuttaako uudelleenlataustapa siihen korjaantuuko ongelma vai ei?

**Comment by katja-moilanen** [comment]
En ole keksinyt säännönmukaisuutta. Nyt näyttäisi siltä, että jos jaksaa riittävän monesti uudelleenlatailla näyttöä (välillä riittää kerta, välillä pitää useammin), niin saa tavallisen lisäys pop up -ikkunan näkyviin kaikilla selaimilla.

Vaihdan majoriksi

**Comment by katja-moilanen** [comment]
Ongelma edelleen olemassa.

**Comment by matti-heinonen** [comment]
Ongelma edelleen olemassa.

**Comment by blueScreenVC** [comment]
Sama kuin #627. Ei ole toistunut.

**Comment by katja-moilanen** [comment]
Tämä toistui testien aikana sen verran usein, etten sulje tätä. Kuten ylläolevasta keskustelusta selviää, ei löytynyt mitään säännönmukaisuutta, miksi näin tapahtui välillä.

**Comment by blueScreenVC** [comment]
Tämänhetkisellä kehitysversiolla ongelma ei toistu selaimilla Chrome, Chromium & Firefox.
