### ISSUE TITLE
Tallennuksessa "turha" virheilmoitus

### ISSUE THREAD

**Issue by katja-moilanen** [Tietoarkisto/metka#436]
Käyttäjä tallensi tiedot asiasanojen lisäämisen jälkeen ja sulki ilmoituksen tallennuksen onnistumisesta ruksilla. Käyttäjä tallensi heti tämän jälkeen tiedot uudelleen ilman, että teki niihin mitään muutoksia. Tuli seuraava ilmoitus: Tallennus suoritettu mutta tallennettavasta datasta löydettiin virheitä tai dataan tehtiin automaattisia muutoksia.

**Comment by blueScreenVC** [comment]
Ei toistu, tulee “Lomakkeella ei ollut tallennettavia muutoksia”. Kokeiltu chrome & chromium & firefox.

**Comment by katja-moilanen** [comment]
Tämä ei ole enää toistunut vuoden 2016 testauksessa. Suljen tämän issuen.
