### ISSUE TITLE
Abstraktin kirjoituskenttään ilmestyy teksti "Drag Image Here"

### ISSUE THREAD

**Issue by katja-moilanen** [Tietoarkisto/metka#438]
![drag_image_here](https://cloud.githubusercontent.com/assets/8694364/10485997/9f19939c-7295-11e5-8f32-27b842ea5553.png)

**Comment by juusokoH** [comment]
En saa toistettua

**Comment by Quu-Ukko** [comment]
Suljetaan ja avataan udelleen jos ongelma tulee taikaisin
