### ISSUE TITLE
Poistettu julkaisu jää osaksi luonnostilassa olevaa aineisto, vaikka sen tulisi poistua suoraviivaisesti.

### ISSUE THREAD

**Issue by katja-moilanen** [Tietoarkisto/metka#448]

**Comment by katja-moilanen** [comment]
ongelma edelleen olemassa

**Comment by samuhynynen** [comment]
Poistetun julkaisun viittaustiedot hävitetään aineistolta julkaisun poiston yhteydessä. https://github.com/Tietoarkisto/metka/commit/d2ed114ccccd076cf9caab99772bb09a5879a31e
