### ISSUE TITLE
Poistettu julkaisu jää osaksi hyväksyttyä aineistoa.

### ISSUE THREAD

**Issue by katja-moilanen** [Tietoarkisto/metka#449]
Piti olla niin, että julkaisun tiedot poistuvat aineistolta ja aineiston kuvailun versionumeroa kasvatetaan automaattisesti.

**Comment by katja-moilanen** [comment]
ongelma edelleen olemassa

**Comment by samuhynynen** [comment]
Poistetun julkaisun viittaustiedot hävitetään aineistolta julkaisun poiston yhteydessä.
