### ISSUE TITLE
Vastausprosentti-kenttää ei kuulu olla kvaliaineistoilla

### ISSUE THREAD

**Issue by katja-moilanen** [Tietoarkisto/metka#458]

**Comment by katja-moilanen** [comment]
ongelma edelleen olemassa

**Comment by juusokoH** [comment]
Vastausprosentille (resprate) on nyt lisätty custom javascript-tiedosto. Jotta muutos tulee voimaan, tulee resprate-kentälle antaa displayTypen arvoksi "CUSTOM_JS". Tämä muutos on puskettu gittiin ylläolevassa commitissa.
