### ISSUE TITLE
Vanhojen revisioiden palauttamisominaisuus puuttuu...

### ISSUE THREAD

**Issue by katja-moilanen** [Tietoarkisto/metka#479]
...tai sitten emme vain keksi kuinka se tapahtuu.

**Comment by LaKulmala** [comment]
JSON-importeista päädyttiin tulokseen että niitä ei tehdä joten tämä on käytännössä luettu samaan kategoriaan. Tällä hetkellä edelliseen revisioon palaaminen onnistuu helposti tietokannasta mutta jos tähän joku muu ratkaisu päädytään tekemään niin järkevin olisi ehkä Data-adminille painike jolla revision voisi poistaa täysin kannasta joka viimeisimmän revision poiston yhteydessä palauttaisi revisioitavan objektin käyttämään edellistä hyväksyttyä revisiota.

**Comment by katja-moilanen** [comment]
ongelma edelleen olemassa

**Comment by matti-heinonen** [comment]
Luodaan uusi uusin versio kopioimalla halutun revision sisältö siihen.
