### ISSUE TITLE
Eksperttihaussa ei pysty hakemaan ylipäänsä aineiston viimeisintä revisiota eikä myöskään aineiston viimeisintä hyväksyttyä revisiota - raporttien tuottaminen ei onnistu.

### ISSUE THREAD

**Issue by katja-moilanen** [Tietoarkisto/metka#484]

**Comment by LaKulmala** [comment]
Käsitetasolla viimeisin hyväksytty revisio ei mielestäni kuulu yksittäisen revision tietoihin. Luonnollisin tapa hoitaa tämä on tehdä datan käsittelyä raportin muodostuksen yhteydessä ja poistaa ei halutut tulokset.

**Comment by matti-heinonen** [comment]
Lassen ehdottama ratkaisu ei ole sopiva. Kantaan tulee syntymään ajan myötä hyvin paljon revisioita. Niiden yli iteroiminen on liian hidasta.

**Comment by juusokoH** [comment]
Lisättiin uusi kolumni RevisionEntityyn. Indeksoidaan nimellä state.latest:<approved|draft|false>. Dokumentoitu metkan ohjeet-sivulle.
