### ISSUE TITLE
Aineistonhaku antaa virheilmoituksen (saattaa liittyä "erikoismerkkeihin" kuten kauttaviivaan tai yhdysviivaan)

### ISSUE THREAD

**Issue by katja-moilanen** [Tietoarkisto/metka#490]
HTTP Status 500 - Request processing failed; nested exception is java.lang.IllegalArgumentException: unexpected end-of-string

---

type Exception report
message Request processing failed; nested exception is java.lang.IllegalArgumentException: unexpected end-of-string
description The server encountered an internal error that prevented it from fulfilling this request.
exception 
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalArgumentException: unexpected end-of-string
    org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:965)
    org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:855)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
    org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:829)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
    org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
    org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
    org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
    org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103)
    org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
    org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154)
    org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)
    org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50)
    org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:106)
    org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter.doFilter(AbstractPreAuthenticatedProcessingFilter.java:107)
    org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
    org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
    org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
    org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:343)
    org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)
    org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
    org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:106)
root cause 
java.lang.IllegalArgumentException: unexpected end-of-string
    org.apache.lucene.util.automaton.RegExp.next(RegExp.java:856)
    org.apache.lucene.util.automaton.RegExp.parseCharExp(RegExp.java:1002)
    org.apache.lucene.util.automaton.RegExp.parseSimpleExp(RegExp.java:997)
    org.apache.lucene.util.automaton.RegExp.parseCharClassExp(RegExp.java:929)
    org.apache.lucene.util.automaton.RegExp.parseComplExp(RegExp.java:917)
    org.apache.lucene.util.automaton.RegExp.parseRepeatExp(RegExp.java:887)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:880)
    org.apache.lucene.util.automaton.RegExp.parseInterExp(RegExp.java:873)
    org.apache.lucene.util.automaton.RegExp.parseUnionExp(RegExp.java:867)
    org.apache.lucene.util.automaton.RegExp.parseSimpleExp(RegExp.java:958)
    org.apache.lucene.util.automaton.RegExp.parseCharClassExp(RegExp.java:929)
    org.apache.lucene.util.automaton.RegExp.parseComplExp(RegExp.java:917)
    org.apache.lucene.util.automaton.RegExp.parseRepeatExp(RegExp.java:887)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:880)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:881)
    org.apache.lucene.util.automaton.RegExp.parseInterExp(RegExp.java:873)
    org.apache.lucene.util.automaton.RegExp.parseUnionExp(RegExp.java:867)
    org.apache.lucene.util.automaton.RegExp.<init>(RegExp.java:406)
    org.apache.lucene.search.RegexpQuery.<init>(RegexpQuery.java:90)
    org.apache.lucene.search.RegexpQuery.<init>(RegexpQuery.java:79)
    org.apache.lucene.search.RegexpQuery.<init>(RegexpQuery.java:69)
    org.apache.lucene.queryparser.flexible.standard.builders.RegexpQueryNodeBuilder.build(RegexpQueryNodeBuilder.java:41)
    org.apache.lucene.queryparser.flexible.standard.builders.RegexpQueryNodeBuilder.build(RegexpQueryNodeBuilder.java:31)
    org.apache.lucene.queryparser.flexible.core.builders.QueryTreeBuilder.processNode(QueryTreeBuilder.java:186)
    org.apache.lucene.queryparser.flexible.core.builders.QueryTreeBuilder.process(QueryTreeBuilder.java:125)
    org.apache.lucene.queryparser.flexible.core.builders.QueryTreeBuilder.process(QueryTreeBuilder.java:118)
    org.apache.lucene.queryparser.flexible.core.builders.QueryTreeBuilder.process(QueryTreeBuilder.java:118)
    org.apache.lucene.queryparser.flexible.core.builders.QueryTreeBuilder.process(QueryTreeBuilder.java:118)
    org.apache.lucene.queryparser.flexible.core.builders.QueryTreeBuilder.process(QueryTreeBuilder.java:118)
    org.apache.lucene.queryparser.flexible.core.builders.QueryTreeBuilder.build(QueryTreeBuilder.java:218)
    org.apache.lucene.queryparser.flexible.standard.builders.StandardQueryTreeBuilder.build(StandardQueryTreeBuilder.java:82)
    org.apache.lucene.queryparser.flexible.standard.builders.StandardQueryTreeBuilder.build(StandardQueryTreeBuilder.java:53)
    org.apache.lucene.queryparser.flexible.core.QueryParserHelper.parse(QueryParserHelper.java:258)
    org.apache.lucene.queryparser.flexible.standard.StandardQueryParser.parse(StandardQueryParser.java:168)
    fi.uta.fsd.metkaSearch.commands.searcher.expert.ExpertRevisionSearchCommand.<init>(ExpertRevisionSearchCommand.java:151)
    fi.uta.fsd.metkaSearch.commands.searcher.expert.ExpertRevisionSearchCommand.build(ExpertRevisionSearchCommand.java:92)
    fi.uta.fsd.metkaSearch.commands.searcher.expert.ExpertRevisionSearchCommand.build(ExpertRevisionSearchCommand.java:79)
    fi.uta.fsd.metka.search.impl.RevisionSearchImpl.performBasicSearch(RevisionSearchImpl.java:293)
    fi.uta.fsd.metka.search.impl.RevisionSearchImpl.search(RevisionSearchImpl.java:71)
    sun.reflect.GeneratedMethodAccessor224.invoke(Unknown Source)
    sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    java.lang.reflect.Method.invoke(Method.java:606)
    org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
    org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
    org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
    org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
    org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
    org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
    com.sun.proxy.$Proxy72.search(Unknown Source)
    fi.uta.fsd.metka.mvc.services.impl.RevisionServiceImpl.search(RevisionServiceImpl.java:220)
    sun.reflect.GeneratedMethodAccessor223.invoke(Unknown Source)
    sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    java.lang.reflect.Method.invoke(Method.java:606)
    org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
    org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
    org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
    org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
    org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
    org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:64)
    org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
    com.sun.proxy.$Proxy73.search(Unknown Source)
    fi.uta.fsd.metka.mvc.controller.RevisionController.search(RevisionController.java:117)
    sun.reflect.GeneratedMethodAccessor222.invoke(Unknown Source)
    sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    java.lang.reflect.Method.invoke(Method.java:606)
    org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215)
    org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
    org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:743)
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:672)
    org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:82)
    org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:933)
    org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:867)
    org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:953)
    org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:855)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
    org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:829)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
    org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
    org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
    org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
    org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103)
    org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
    org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154)
    org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)
    org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50)
    org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:106)
    org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter.doFilter(AbstractPreAuthenticatedProcessingFilter.java:107)
    org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
    org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
    org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
    org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:343)
    org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)
    org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
    org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:106)
note The full stack trace of the root cause is available in the Apache Tomcat/7.0.52 (Ubuntu) logs.

---

Apache Tomcat/7.0.52 (Ubuntu)

**Comment by katja-moilanen** [comment]
ongelma edelleen olemassa

**Comment by blueScreenVC** [comment]
Millaisella hakulauseella virheilmoitus saatiin aikaiseksi?

**Comment by katja-moilanen** [comment]
Kyseessä on lomakkeella suoritettu haku, jossa on kauttaviiva "/" esimerkiksi Havainto/aineistoyksiköksi valitaan "Tapahtuma/prosessi/ilmiö". Tällöin tulee ilmoitus SEARCH_FAILED. Enää ei siis tule tuota pitkää virheilmoitusta.

Jos haettavassa tekstissä on sulkumerkki "(", niin Metka ei löydä mitään, mutta vaikka tietoa olisikin kanssa (esim. sarjan nimessä on sulkumerkki).

Yhdysviiva näyttäisi toimivan.
