### ISSUE TITLE
Metkan Tiedostojen Hallinta -sivun lataus hidasta aineistoilla joilla on useita liitetiedostoja

### ISSUE THREAD

**Issue by matti-heinonen** [Tietoarkisto/metka#497]
Metkan Tiedostojen Hallinta -sivun lataus hidastuu huomattavasti (~330s) aineistolla FSD2305 jolla on 625 tiedostoliitettä.

**Comment by matti-heinonen** [comment]
Edelleen olemassa.

**Comment by juusokoH** [comment]
Pitäisi olla nopeampi sivutuksen toteutuksen jälkeen.

**Comment by Quu-Ukko** [comment]
Sama ongelma kuin https://github.com/Tietoarkisto/metka/issues/221 sivutus hidastuu suurien tiedostomäärien kanssa.

**Comment by henrisu** [comment]
Tiedostoliitteiden sivutusta optimoitu, ks. #221.
