### ISSUE TITLE
Tallennettu eksperttihaku ei poistu UI:sta kun painaa poista (häviää kyllä kannasta)

### ISSUE THREAD

**Issue by matti-heinonen** [Tietoarkisto/metka#507]
Tallennettu experttihaku: kun tallenetun haun poistaa, se ei poistu UI:sta vaikka ilmeisesti poistuu kannasta. Jos yrittää poistaa toisen kerran saa NullPointerExceptionin. Jos painaa F5 niin huomaa että haku on poistunut. Sama tulos sekä IE että Firefox.

**Comment by matti-heinonen** [comment]
Edelleen olemassa.

**Comment by katja-moilanen** [comment]
Ongelma edelleen olemassa

**Comment by blueScreenVC** [comment]
Eksperttihaun poisto korjattu ( #649 ).
