### ISSUE TITLE
Poistetut tiedosto eivät näy Aineiston poistetut tiedostot -taulukosta

### ISSUE THREAD

**Issue by katja-moilanen** [Tietoarkisto/metka#522]

**Comment by LaKulmala** [comment]
Testattu tietoarkistolla ja poistetut tiedostot toimivat aivan oikein. Vaatii uuden tarkistuksen ja mielellään esimerkkitapauksia. HUOM! Jos tiedostosta ei ole hyväksyttyjä revisioita niin tiedosto poistoo kokonaan jolloin listalle ei tietenkään jää mitään merkintöjä.

**Comment by katja-moilanen** [comment]
Kokeilinpa tätä nyt sitten vielä yhden kerran hyväksytylle aineistolle IE:llä eikä tuo poisto toiminut. Tein hyväksytystä aineistosta luonnoksen. Menin tiedostojen hallintaan. Klikkasin tiedostoliitettä, jonka halusin poistaa, kirjoitin kommentti-kenttään "tiedoston poisto" ja painoin liitteellä poista-nappia. Metka kysyi haluatko varmasti poistaa, vastaus kyllä. Tiedostoliite meni tällä kertaa vain "hyväksytty"-tilaan, eikä poistunut lainkaan.

![poistettu_onkin_hyvaksytty](https://cloud.githubusercontent.com/assets/8694364/10906781/e0c4c644-822c-11e5-9106-100047b8cf8c.PNG)


Yritin tehdä aineistosta uudestaan luonnosta katsoakseni mitä sitten tapahtuu, mutta sainkin sitten Internal Server Errorin.
![internal_server_error_taasen](https://cloud.githubusercontent.com/assets/8694364/10906787/edad5baa-822c-11e5-9027-64634a146551.PNG)

Edes uloskirjautuminen Metkasta ei onnistunut.

**Comment by LaKulmala** [comment]
Tuossa ylemmässä tapauksessa poistit pelkästään liitteen luonnoksen. Sekä muuttujista että liitteistä tehdään automaattisesti luonnos aineiston uuden luonnoksen teon yhteydessä. Tätä toivottiin koska oli "työlästä" painaa edit nappulaa kun halusi käsitellä muuttujia. Luonnokset poistetaan hyväksymisen yhteydessä jos niissä ei ole ollenkaan muutoksia. Eli liite pitää poistaa kahteen kertaan.

Toisessa kohdassa haluaisin vähän lisätietoja, kuvauksen perusteella sain käsityksen että koitit tehdä luonnoksen jo luonnostilassa olleesta aineistosta? Virhe vaikuttaa joka tapauksessa enemmän Tomcatin (eli palvelinympäristön) virheeltä ja ilman logeja en osaa sen enempää sanoa.

Uloskirjautuminen on todettu myös palavereissa moneen kertaan että sen toteuttaminen shibbolethiin ilman selaimen sulkemistarvetta on niin vaikeaa ettei sitä tarvitse tässä lähteä tekemään. Jos uloskirjautuminen ei toiminut edes selaimen sulkemalla niin sitten voidaan tutkia tarkemmin.

**Comment by katja-moilanen** [comment]
Jäi näköjään kirjaamatta, että Hyväksyin aineiston ennen kuin yritin tehdä siitä taas luonnosta.

**Comment by katja-moilanen** [comment]
Yritin edelleen poistaa samaa tiedostoa samalta aineistolta.

Alkutila:
![alkutila](https://cloud.githubusercontent.com/assets/8694364/10907182/9a32fcba-8230-11e5-8a27-91587afab76a.PNG)

Tiedoston tiedot auki:
![auki](https://cloud.githubusercontent.com/assets/8694364/10907185/a8ed8540-8230-11e5-857d-6e193bf26d61.PNG)

Painoin poista nappia:
![poistamisenvarmistus](https://cloud.githubusercontent.com/assets/8694364/10907192/b52120ba-8230-11e5-86f8-a42670d74c65.PNG)
ja ylläolevasta dialogista "Kyllä".

Tiedostoliitteen tilaksi tuli HYVÄKSYTTY
![hyvaksyttyna](https://cloud.githubusercontent.com/assets/8694364/10907207/cc6fff16-8230-11e5-8b67-f607a7f87807.PNG)

Hyväksyin koko aineiston:
![onnistui](https://cloud.githubusercontent.com/assets/8694364/10907214/dae57242-8230-11e5-9a7d-2d502389afe7.PNG)

Tiedostoliite on edelleen osa aineistoa:
![edelleen_aineistolla](https://cloud.githubusercontent.com/assets/8694364/10907216/e9fe4e34-8230-11e5-9244-e19c624774e2.PNG)

Tein uuden luonnoksen (ei tullut nyt virheilmoituksia) ja tiedostoliite on edelleen osa aineistoa:
![uusi_luonnos](https://cloud.githubusercontent.com/assets/8694364/10907252/2807f162-8231-11e5-8718-8d6efb8c8a81.PNG)

**Comment by katja-moilanen** [comment]
Nyt vasta luin huolella kommenttisi. Eli tiedosto pitää poistaa kahteen kertaan, jotta se poistuisi. Ilmankos en ole saanut poistoa toimimaan :). Nyt kun ohjeistit, tiedostot poistuu ja siirtyy. Kiitos.
