### ISSUE TITLE
Käyttäjä yritti päivittää datatiedoston, mutta sai virheilmoituksen. Data on siirtynyt oikein kansioon, mutta muuttujien tiedot eivät ole päivittyneet.

### ISSUE THREAD

**Issue by katja-moilanen** [Tietoarkisto/metka#541]
Virheilmoituksesta on valitettavasti vain kuvakaappaus:
![datatiedoston_paivitysvirhe](https://cloud.githubusercontent.com/assets/8694364/10758205/8886f67e-7cb8-11e5-99de-bd9c7e4d31bb.PNG)

**Comment by LaKulmala** [comment]
Tiedosto oli rikki, joten testitapauksesta ei voida vetää mitään johtopäätöksiä.
