### ISSUE TITLE
DDI Export: dataKind ei käänny (tulee suomeksi kaikkiin kieliversioihin)

### ISSUE THREAD

**Issue by katja-moilanen** [Tietoarkisto/metka#547]

**Comment by katja-moilanen** [comment]
Ongelma edelleen olemassa

**Comment by samuhynynen** [comment]
Datakind_list -pudotusvalikon arvoille lisätty käännökset study_configuration.jsoniin. Onnistuu siis näin:

`	"datakind_list": {
			"key": "datakind_list",
			"type": "VALUE",
			"default": "1",
			"options": [
				{
					"&title": {
						"default": "Kvantitatiivinen",
						"en": "Quantitative",
						"sv": "Kvantitativ"
					},
					"value": "1"
				}, {
					"&title": {
						"default": "Kvalitatiivinen",
						"en": "Qualitative",
						"sv": "Kvalitativ"
					},
					"value": "2"
				}
			]
		},`
