### ISSUE TITLE
Aineistosta muutettiin vain asiasanoja ja silti revisiohistoriassa näkyi tiedostoliitteiden muutos.

### ISSUE THREAD

**Issue by katja-moilanen** [Tietoarkisto/metka#561]
![tiedostoliitteen_tiedot_muuttuneet](https://cloud.githubusercontent.com/assets/8694364/10760845/42b38d88-7cc7-11e5-996c-12cee9899448.PNG)

**Comment by katja-moilanen** [comment]
Ongelma edelleen olemassa

**Comment by juusokoH** [comment]
Korjattu [tässä commitissa](https://github.com/Tietoarkisto/metka/commit/c6a0638e9ac236cfadbfba4a9a931db9e8e9b262)
