### ISSUE TITLE
Tekstikorjaus: DDI-exportin enkkupuolelle Tietoarkiston nimi käännetyksi oikein

### ISSUE THREAD

**Issue by katja-moilanen** [Tietoarkisto/metka#582]

**Comment by katja-moilanen** [comment]
Jos biblcit on helposti muokattavissa, tämä on minor. Jos muokkaus on vaikeaa, tämä on major.

**Comment by samuhynynen** [comment]
Nyt tietoarkiston nimi näyttäisi tulevan oikein englanninkieliseen DDI-exporttiin: _Finnish Social Science Data Archive_
