### ISSUE TITLE
Muuttujilta katoaa muokkauspäivämääriä

### ISSUE THREAD

**Issue by katja-moilanen** [Tietoarkisto/metka#608]
Ensimmäisessä revisiossa käyttäjä oli tehnyt muutoksia muuttujan metadataan ja hyväksynyt aineiston (muokkauspäivämäärät näkyivät oikein). Käyttäjä teki aineistosta uuden revision ja vei muokatun datan aineistolle (muutoksia esim. muuttujan/luokkien selitteisiin). Lisäksi hän teki aineiston metadataan muutoksia toisille muuttujille. Käyttäjä hyväksyi aineiston. Muuttujien tietojen viimeisin muokkauspvm katosi niiltä muuttujilta joihin oli tehty muutoksia datan kautta.

**Comment by Quu-Ukko** [comment]
Testattu ja havaittu toimivaksi. Suljen issuen.
