### ISSUE TITLE
DDI export: merkki < muuttuu &lt; esim. <br> sijaan lukee &lt;br>

### ISSUE THREAD

**Issue by katja-moilanen** [Tietoarkisto/metka#610]

**Comment by samuhynynen** [comment]
Validissa XML-tiedostossa < -merkki saa esiintyä ainoastaan kommenttina tai merkkidatana. Rivinvaihdot näkyvät nyt DDI-exportissa, kuten pitääkin ( <br/> ), mutta elementtien sisällä < -merkit muutetaan entiteettiviittauksiksi (&lt;), jotta XML-tiedosto olisi validi.
