### ISSUE TITLE
API: claimRevision ei anna JSON-virhettä vaan nostaa poikkeuksen, jos kohteena on revisio, jota ei ole olemassa

### ISSUE THREAD

**Issue by matti-heinonen** [Tietoarkisto/metka#631]
Kutsuva ohjelma ei pysty toipumaan mielekkäästi virheestä.

<pre>Request (json):
{
  "key": {
    "id": 92460,
    "no": 1
  },
  "authentication": <poistettu>
}</pre>

Response (raw):

<pre>org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.security.access.AccessDeniedException: Access is denied
        org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:965)
        org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:855)
        javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
        org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:829)
        javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
        org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:106)
<p><b>root cause</b> <pre>org.springframework.security.access.AccessDeniedException: Access is denied
        org.springframework.security.access.vote.AffirmativeBased.decide(AffirmativeBased.java:83)
        org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:206)
        org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:60)
        org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
        com.sun.proxy.$Proxy74.claimRevision(Unknown Source)
        fi.uta.fsd.metkaExternal.APIController.claimRevision(APIController.java:250)
        sun.reflect.GeneratedMethodAccessor162.invoke(Unknown Source)
        sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        java.lang.reflect.Method.invoke(Method.java:606)
        org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215)
        org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
        org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
        org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:743)
        org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:672)
        org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:82)
        org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:933)
        org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:867)
        org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:953)
        org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:855)
        javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
        org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:829)
        javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
        org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:106)
</pre></p><p><b>note</b> <u>The full stack trace of the root cause is available in the Apache Tomcat/7.0.52 (Ubuntu) logs.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.52 (Ubuntu)</h3></body></html>
urllib2.HTTPError: HTTP Error 500: Internal Server Error
Traceback (most recent call last):
  File "/home/optech/toni/metka/metka_tools-env/bin/metka", line 9, in <module>
    load_entry_point('metkatools==0.1', 'console_scripts', 'metka')()
  File "/home/optech/toni/metka/metkatools/metkatools/scripts/metka/__main__.py", line 417, in main
    execute(metka_api, params)
  File "/home/optech/toni/metka/metkatools/metkatools/scripts/metka/__main__.py", line 335, in execute
    exec_fun(metka_api, params)
  File "/home/optech/toni/metka/metkatools/metkatools/scripts/metka/__main__.py", line 191, in claim_revision
    params.revision_no
  File "/home/optech/toni/metka/metkatools/metkatools/metka_client.py", line 38, in claim_revision
    .claim_revision(revisionable_id, revision_no)
  File "/home/optech/toni/metka/metkatools/metkatools/metka_api.py", line 59, in claim_revision
    return self.call('/claimRevision', args, method='POST')
  File "/home/optech/toni/metka/metkatools/metkatools/metka_api.py", line 25, in call
    last_response = super(MetkaApi, self).call(path, data, method)
  File "/home/optech/toni/metka/metkatools/metkatools/json_interface.py", line 55, in call
    resp = urllib2.urlopen(req, request_raw)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 500: Internal Server Error</pre>

**Comment by Quu-Ukko** [comment]
Ongelma esiintyy myös, kun yrittää tallentaa revisiota, jota ei ole claimattu api-käyttäjälle. Eli ohjelma ei ilmoita virheestä kauniisti vaan heittää poikkeuksen ja stacktracen silmille.

**Comment by samuhynynen** [comment]
Olemattoman revision haltuunottoyritys palauttaa nyt JSON-ilmoituksen, josta käy ilmi, ettei revisiota löytynyt.
