### ISSUE TITLE
API: claim_revision nostaa AccessDeniedException:n jos kohteena on revisio jota ei ole olemassa

### ISSUE THREAD

**Issue by matti-heinonen** [Tietoarkisto/metka#632]
Yleensä AccessDeniedExceptionin saa, jos revisionable ei ole käsittelijän hallussa. Tässä tapauksessa se on harhaanjohtava.

Liittyy tapaukseen #631 .

**Comment by samuhynynen** [comment]
Olemattoman revision haltuunottoyritys API:n kautta ei nosta enää poikkeusta, vaan palauttaa seuraavanlaisen vasteen:

{"authenticated":true,"result":"REVISION_NOT_FOUND","exception":null,"response":{"result":{"result":"REVISION_NOT_FOUND","message":null},"data":null,"configuration":null,"gui":null}}
