### ISSUE TITLE
Aineiston lomakehaun rajaus hyväksyttyjä, luonnoksia, poistettuja ei toimi

### ISSUE THREAD

**Issue by katja-moilanen** [Tietoarkisto/metka#642]
Jos valittuna on vain hyväksytyt ja luonnokset, löytyvät silti poistetutkin.

**Comment by matti-heinonen** [comment]
Ei onnistu myöskään API:n kautta.

**Comment by juusokoH** [comment]
En saa ainakaan toistettua enää - korjaantunut indekserin korjausten myötä.
