### ISSUE TITLE
Sarjan poistaminen ei onnistu, vaikkei sarjaan liity yhtään aineistoa

### ISSUE THREAD

**Issue by katja-moilanen** [Tietoarkisto/metka#652]
Metkan instanssissa on vain yksi käyttäjä. Hän lisää sarjan ja hyväksyy sen. Käyttäjä ei liitä sarjaa yhteenkään aineistoon. Hän yrittää poistaa sarjan. Ensin tulee ilmoitus: Haluatko varmasti poistaa jne. Tämän jälkeen tulee virheilmoitus: Rajoitteet estivät poiston suorittamisen QUERY STUDY series.value:{id}

**Comment by juusokoH** [comment]
Onko tämä vielä ongelma?

**Comment by Quu-Ukko** [comment]
On yhä ongelma. Loin sarjan instanssiin jossa oli ennestään aineistoja ja sarjoja ja sain tämän saman virheilmoituksen.

**Comment by juusokoH** [comment]
Onko rajoite konfiguroitu oikein? Jos tarkoituksena on se, että sarjaa ei voi poistaa jos sillä on yhtään hyväksyttyä (ei poistettua?) liittyvää aineistoa, niin tarvitaan QUERY-tyyppinen rajoite, jonka sisältö on "+key.configuration.type:STUDY +state.removed:FALSE +series.value:{id}" ja kohteen tarkistuksissa tulee olla QUERY - IS_EMPTY.

**Comment by Quu-Ukko** [comment]
Ongelma korjaantui vaihtamalla olemassa olevan rajoitteen tilalle yllä olevan queryn.
