### ISSUE TITLE
API: suorituskyky massaoperaatioissa - kohtuuton määrä api-kutsuja tietoja noudettaessa

### ISSUE THREAD

**Issue by matti-heinonen** [Tietoarkisto/metka#662]
Tämä vaikuttaa suoraan järjestelmän suorituskykyyn esimerkiksi massapäivitystilanteessa tai tietojen viemisessä pitkäaikaissäilytykseen. Testissä käytetyn yhden aineiston tietojen noutaminen edellytti lähes 200 API-kutsua.  Kutsujen määrä luultavasti kasvaa suoraan sen mukaan montako muuttujaa, liitettä ja julkaisua liittyy aineistoon. 

Jos nouto-operaatio pitää tehdä koko aineistomassalle, niin ajo tulee kestämään ikuisuuden.

**Comment by juusokoH** [comment]
Kutsuja niputettu - kts. fullViewRevision-endpoint
