### ISSUE TITLE
Aikaan perustuvia herätteitä ei ole toteutettu ollenkaan

### ISSUE THREAD

**Issue by matti-heinonen** [Tietoarkisto/metka#734]
En löydä Metkasta minkäänlaista ajastettua toiminnallisuutta/aikaan perustuvia sisällöntarkasteluja. 

Vai olenko ymmärtänyt väärin? Kuinka täytän ja mitä tapahtuu, kun Arkistointisopimus-välilehdelle viedään tiedot kenttiin
- Jos heräte, ilmoituspvm
- Herätteen saaja
- Herätteen selite

Pitäisi lähteä AMQP-viesti B7 ja sähköpostia herätteen saajalle.

Samaten viestit B1, B2 ja B8 edellyttänevät jonkinlaista periodista tarkastelua. En löydä toteutusta enkä dokumentaatiota. Katso myös #623.

**Comment by Quu-Ukko** [comment]
Heräte B7 on toteutettu niin suljen tämän issuen. Puuttuvista herätteistä on erikseen issue #624
