### ISSUE TITLE
Eksperttihaku ei toimi mappien kentällä binderid

### ISSUE THREAD

**Issue by katja-moilanen** [Tietoarkisto/metka#751]

**Comment by juusokoH** [comment]
Saan ainakin itse tuloksia syntaksilla +binderid:{xxx xxx}. Binderid on integer-tyyppinen kenttä, joten haku tulee tapahtua tuolla syntaksilla.

**Comment by Quu-Ukko** [comment]
Sivukomenttina tulevaisuuden varalle syntaksi on +binderid:[1338 9001]
