### ISSUE TITLE
Eksperttihaku julkaisuista ei toimi ainakaan seuraavilla kentillä: publicationyear, publicationid

### ISSUE THREAD

**Issue by katja-moilanen** [Tietoarkisto/metka#752]

**Comment by juusokoH** [comment]
Saan ainakin itse tuloksia syntaksilla +publicationyear:{xxx xxx}. Molemmat näistä kentistä ovat integer-tyyppisiä kenttiä, joten haku tulee tapahtua tuolla syntaksilla.
