### ISSUE TITLE
GUI-dokumentaatio, hidden -avain

### ISSUE THREAD

**Issue by Quu-Ukko** [Tietoarkisto/metka#760]
Hidden avaimen yhteydessä mainitaan että "Mikäli arvo on true, tätä Containeria ei oletusarvoisesti näytetä käyttöliittymässä.". Dokumentaatiossa ei ole mainintaa miten piilotettujen kenttien näkyvyyttä hallinnoidaan.

**Comment by samuhynynen** [comment]
Kun kenttä on konfiguroitu piilotetuksi käyttöliittymässä, kenttää ei yksinkertaisesti näytetä käyttöliittymässä, eikä sen näkyvyydessä nähdäkseni ole sen suurempaa hallinnoitavaa. Mikäli piilotetut kentät tahtoo takaisin näkyviin, tulee hidden -avaimen arvo (boolean totuusarvo) muuttaa takaisin epätodeksi (_false_).
