### ISSUE TITLE
Wikistä puuttuu oma sivu tutoriaaleille/esimerkeille

### ISSUE THREAD

**Issue by Quu-Ukko** [Tietoarkisto/metka#766]
Wikissä olisi hyvä olla tutoriaaleja joissa käydään alusta loppuun läpi erilaisten elementtien lisääminen Metkaan. Tutoriaaleissa olisi hyvä siis käsitellä yhdessä datakonfiguraation muokkaamista ja guikonfiguraation muokkaamista. 

Varsinkin seuraavista asioista tarvittaisiin esimerkit:
- Uuden kentän luominen
- Modaali-ikkunan luominen
- Sarjoitusten käyttö
- Valintalistojen luominen alusta loppuun (tavallinen lista, viittauslista, alilista)

**Comment by juusokoH** [comment]
https://github.com/Tietoarkisto/metka/wiki/Esimerkkej%C3%A4 Kerätään esimerkkejä tänne.

**Comment by juusokoH** [comment]
Näistä tapauksista löytyy nyt yksinkertaiset esimerkit. Lisäkonfiguraatioon on merkattu linkit olemassaoleviin dokumentaatioihin. Lisäksi käytännön esimerkkejä löytyy olemassaolevasta koodista ja data/GUI -konfiguraatioista.
