### ISSUE TITLE
Aineistoon (STUDY) ja submissionid:n kohdistuva haku aiheuttaa poikkeuksen

### ISSUE THREAD

**Issue by Quu-Ukko** [Tietoarkisto/metka#781]
Seuraava hakulauseke aiheuttaa poikkeuksen sekä apihaussa että GUI:n eksperttihaussa: key.configuration.type:STUDY AND submissionid:*

**Comment by juusokoH** [comment]
submissionid on merkattu datakonfiguraatiossa INTEGER-tyyppiseksi kentäksi, jolloin täytyy hakea esim. submissionid: {0 10000}.
