### ISSUE TITLE
APIn kautta tehty luvaton poistoyritys aiheuttaa poikkeuksen

### ISSUE THREAD

**Issue by Quu-Ukko** [Tietoarkisto/metka#795]
API-komento removeRevision aiheuttaa poikkeuksen, kun yrittää tehdä sen käyttäjällä jonka rooli metka:basic-user.

**Comment by samuhynynen** [comment]
Kopio issuesta #797, ratkaistu versiossa https://github.com/Tietoarkisto/metka/commit/fdb655ff2da25825aa246df5bc8bd38947e93f2e

**Comment by samuhynynen** [comment]
API-käyttäjälle lisätty roolin tarkistus removeRevision-endpointtiin. Luvaton poistoyritys ei palauta enää poikkeusta.
