### ISSUE TITLE
API:n kautta tehty luvaton palautusyritys aiheuttaa poikkeuksen

### ISSUE THREAD

**Issue by Quu-Ukko** [Tietoarkisto/metka#797]
API-komento restoreRevision aiheuttaa poikkeuksen, kun yrittää tehdä sen käyttäjällä jonka rooli metka:basic-user.

**Comment by samuhynynen** [comment]
restoreRevision-endpointtiin lisätty käyttäjän roolin tarkistus. 

https://github.com/Tietoarkisto/metka/commit/fdb655ff2da25825aa246df5bc8bd38947e93f2e
