### ISSUE TITLE
Aineisto, virheet, GUIsta puuttuu painikkeet

### ISSUE THREAD

**Issue by Quu-Ukko** [Tietoarkisto/metka#807]
Siirryttäessä hyväksystä aineistosta luonnokeen GUI:sta puuttuu kokonaan painikkeet.
![virheepuuttuvatcontrollit](https://cloud.githubusercontent.com/assets/10349869/22101417/fadd953a-de3b-11e6-9ae9-1132a423f75f.PNG)

**Comment by juusokoH** [comment]
GUI-konfiguraatiosta tulee muuttaa: STUDY-JSONista Virheet-tabin osiosta "hidePageButtons" falseksi
