### ISSUE TITLE
Study_variables-haussa vargrouptexts.vargrouptext, casequantity ja varquantity eivät toimi

### ISSUE THREAD

**Issue by katja-moilanen** [Tietoarkisto/metka#811]

**Comment by Quu-Ukko** [comment]
Casequantity ja varquantity näyttäisivät toimivan kunhan konfiguraatio tyyppi on määritelty. Vargrouptext ei näytä vastaavan hakuihin, yritetty seuraavilla hakulauseilla: key.configuration.type:STUDY_VARIABLES AND vargrouptexts.vargrouptext:* ja key.configuration.type:STUDY_VARIABLES AND vargrouptexts.vargrouptext:/.*a.*/

**Comment by juusokoH** [comment]
Korjattu, pitäisi toimia uudelleenindeksoinnin jälkeen.
