### ISSUE TITLE
Datakonfiguraatio, rajoitteet menevät solmuun

### ISSUE THREAD

**Issue by Quu-Ukko** [Tietoarkisto/metka#824]
Uusien rajoitteiden luominen näyttäisi sotkevan vanhoja rajoitteita. Testitapauksessa rajoitteet oli määritelty siten, että sarjan nimikentän oli oltava tyhjä jotta voidaan suorittaa looginen poisto. Tässä oli ristiriita vanhan rajoitteen kanssa joka estää revision hyväksymisen jos nimikenttä on tyhjä. Testitapauksessa revision pystyi hyväksymään ilman nimeä.

**Comment by juusokoH** [comment]
Onko vielä ongelma? En saa toistumaan tällä esimerkillä - hyväksyminen ei mene läpi tyhjällä nimellä.

**Comment by Quu-Ukko** [comment]
En saanut itsekkään tätä toistumaan. Suljen issuen
