### ISSUE TITLE
Datakonfiguraatio, rajoitteet, Unique-tyyppisen rajoitteen scope 

### ISSUE THREAD

**Issue by Quu-Ukko** [Tietoarkisto/metka#825]
Dokumentaatiossa ei mainita kuinka laajasti uniikkius tarkastetaan. Tarkastetaanko se vain hyväksytyistä revisioista vai myös luonnoksista?

**Comment by juusokoH** [comment]
Tarkastetaan kaikista saman tyypin (STUDY, SERIES...) revisioista: hyväksytyt, poistetut ja luonnokset
