### ISSUE TITLE
Datakonfiguraatio, rajoitteet, restore operaatio ei toimi

### ISSUE THREAD

**Issue by Quu-Ukko** [Tietoarkisto/metka#826]
Metka ei reagoi Restore-operaation alla oleviin rajoitteisiin.

**Comment by Quu-Ukko** [comment]
Testatut rajoitteet tehtiin FIELD ja VALUE kohdetyypeille, käyttäen kaikkia vaatimusttyyppejä, increasing ja decreasing tyyppejä lukuun ottamatta.

**Comment by juusokoH** [comment]
Onko tarvetta käyttää rajoitteita restore (myös claim ja release) -operaatioilla? Data ei muutu näiden operaation yhteydessä, joten vertailtavaa dataa ei ole.

**Comment by juusokoH** [comment]
Ei toteuteta rajoitteita RESTORE-operaatiolle.
