### ISSUE TITLE
Datakonfiguraatio, rajoitteet, Claim operaatio ei toimi 

### ISSUE THREAD

**Issue by Quu-Ukko** [Tietoarkisto/metka#827]
Metka ei reagoi Claim-operaation alla oleviin rajoitteisiin.

**Comment by Quu-Ukko** [comment]
Testatut rajoitteet tehtiin FIELD ja VALUE kohdetyypeille, käyttäen kaikkia vaatimusttyyppejä, increasing ja decreasing tyyppejä lukuun ottamatta.

**Comment by juusokoH** [comment]
Ei toteuteta rajoitteita CLAIM-operaatiolle.
