### ISSUE TITLE
GUI-konfiguraatio, dokumentaatio, TIME-kentat

### ISSUE THREAD

**Issue by Quu-Ukko** [Tietoarkisto/metka#840]
Dokumentaatiossa ei ole mainintaa että DATE, DATETIME ja TIME tyyppisillä kentillä multiline-avaimen true arvo aiheuttaa kentän arvon häviämisen GUI:sta.

**Comment by blueScreenVC** [comment]
Maininta lisätty multiline -avaimen yhteyteen.
