### ISSUE TITLE
API: Tiedostoliitteitä jää tallentumatta, tiedosto on kuitenkin siirtynyt

### ISSUE THREAD

**Issue by Quu-Ukko** [Tietoarkisto/metka#844]
Kun apilla tallentaa tiedostoliitteitä Metkaan jäävät revisiot välillä syntymättä. Response JSONssa operaation tulos on kuitenkin OPERATION_SUCCESSFUL.  Tiedosto löytyy oikealta paikaltaa /usr/share/metka/files hakemistosta.

Huomasin tämän osana massa-ajoa, joista on aiemmin raportoitu #622.  Massa-ajosta on tallella kaikki loki-tiedostot

**Comment by Quu-Ukko** [comment]
Eli siis tässä tapauksessa GUI:n ei synny riviä lainkaan.

**Comment by Quu-Ukko** [comment]
Ongelma edelleen olemassa ja koskee lähes aina POR-tiedostoja. Reilun sadan aineiston migraatiossa puuttui useita POR-tiedostoja ja yksi pdf.

Testasin versiolla: 2ee64419b5b129ffe8aaccdaa018174619d59a9b

**Comment by juusokoH** [comment]
Korjattu, toimii käyttämällä uutta massCreateFiles API-kutsua
