### ISSUE TITLE
Jos GUI-elementille antaa permission arvon peittyy se kaikilta käyttäjiltä elementistä huolimatta.

### ISSUE THREAD

**Issue by Quu-Ukko** [Tietoarkisto/metka#857]
Eli jos permissions kenttään kirjoittaa, minkä tahansa arvon peittyy kyseinen elementti kaikilta käyttäjiltä roolista huolimatta. Liittenä olevassa konfiguraatiossa on annettu sarjan column-elementille HAS_MINIMUM_PERMISSION -arvo.
[metka_serisies.txt](https://github.com/Tietoarkisto/metka/files/1013664/metka_serisies.txt)

**Comment by Quu-Ukko** [comment]
Testattu versiolla: 4cbcb9c4b4187493cd289199ff6a81e81e2fab48

**Comment by juusokoH** [comment]
Permission-arvo täytyy antaa camelCase-muodossa (hasMinimumPermission). Korjattu dokumentaatioon.
